-- Create table for shops
CREATE TABLE shops_data (
    shop_id NUMBER PRIMARY KEY,
    shop_name VARCHAR2(255)
);

-- Create table for item categories
CREATE TABLE item_categories_data (
    item_category_id NUMBER PRIMARY KEY,
    item_category_name VARCHAR2(255)
);

-- Create table for items
CREATE TABLE items_data (
    item_id NUMBER PRIMARY KEY,
    item_name VARCHAR2(255),
    category_id NUMBER,
    FOREIGN KEY (category_id) REFERENCES item_categories_data(item_category_id)
);

-- Create table for sales transactions
CREATE TABLE sales_transactions (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date DATE,
    date_block_num NUMBER,
    shop_id NUMBER,
    item_id NUMBER,
    item_price NUMBER,
    item_cnt_day NUMBER,
    FOREIGN KEY (shop_id) REFERENCES shops_data(shop_id),
    FOREIGN KEY (item_id) REFERENCES items_data(item_id)
);




select count(*) from sales_transactions;
SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS current_schema FROM dual;
--DROP TABLE sales_transactions CASCADE CONSTRAINTS;
--DROP TABLE items_raw CASCADE CONSTRAINTS;
--DROP TABLE item_categories_raw CASCADE CONSTRAINTS;
--DROP TABLE shops_raw CASCADE CONSTRAINTS;

